# Generated by Django 2.1.2 on 2018-10-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('1', 'Cargo 1'), ('2', 'Cargo 2'), ('3', 'Cargo 3'), ('4', 'Cargo 4'), ('5', 'Cargo 5')], max_length=1)),
                ('photo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.CharField(choices=[('1', 'Emergencia 1'), ('2', 'Emergencia 2'), ('3', 'Emergencia 3'), ('4', 'Emergencia 4'), ('5', 'Emergencia 5')], max_length=1)),
                ('district', models.CharField(choices=[('1', 'Distrito 1'), ('2', 'Distrito 2'), ('3', 'Distrito 3'), ('4', 'Distrito 4'), ('5', 'Distrito 5')], max_length=1)),
                ('province', models.CharField(choices=[('1', 'Provincia 1'), ('2', 'Provincia 2'), ('3', 'Provincia 3'), ('4', 'Provincia 4'), ('5', 'Provincia 5')], max_length=1)),
                ('region', models.CharField(choices=[('1', 'Región 1'), ('2', 'Región 2'), ('3', 'Región 3'), ('4', 'Región 4'), ('5', 'Región 5')], max_length=1)),
                ('magnitude', models.CharField(choices=[('1', 'Magnitud 1'), ('2', 'Magnitud 2'), ('3', 'Magnitud 3'), ('4', 'Magnitud 4'), ('5', 'Magnitud 5')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Agent')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Authority')),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Request'),
        ),
        migrations.AddField(
            model_name='item',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Request'),
        ),
    ]
