# Generated by Django 2.1.2 on 2019-02-14 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='Apellido', max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya ha sido usado'}, max_length=40, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(error_messages={'unique': 'Este teléfono ya ha sido usado'}, max_length=9, unique=True)),
                ('photo_url', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(max_length=175)),
                ('code', models.CharField(max_length=10)),
                ('fcm_token', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('1', 'Cargo 1'), ('2', 'Cargo 2'), ('3', 'Cargo 3'), ('4', 'Cargo 4'), ('5', 'Cargo 5')], max_length=1)),
                ('photo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('image', models.CharField(max_length=40)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaFocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya ha sido usado'}, max_length=40, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('identifier', models.CharField(max_length=11)),
                ('phone', models.CharField(error_messages={'unique': 'Este teléfono ya ha sido usado'}, max_length=9, unique=True)),
                ('photo_url', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(max_length=175)),
                ('code', models.CharField(max_length=10)),
                ('fcm_token', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('RUC_or_DNI', models.CharField(max_length=11)),
                ('amount', models.IntegerField(default=0)),
                ('empresa_focal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EmpresaFocal')),
            ],
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Help')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('total', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=600)),
                ('theme', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('emergency', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=40)),
                ('priority', models.CharField(blank=True, choices=[('Prioridad 1', 'Prioridad 1'), ('Prioridad 2', 'Prioridad 2'), ('Prioridad 3', 'Prioridad 3')], max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2019, 2, 16, 0, 43, 24, 716756))),
                ('closed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('image_accepted', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('receiver_name', models.CharField(blank=True, max_length=30)),
                ('receiver_dni', models.CharField(blank=True, max_length=8)),
                ('receiver_phone', models.CharField(blank=True, max_length=9)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Agent')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Authority')),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
        migrations.AddField(
            model_name='notification',
            name='solicitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
        migrations.AddField(
            model_name='item',
            name='solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
        migrations.AddField(
            model_name='helpitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Item'),
        ),
        migrations.AddField(
            model_name='help',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Item'),
        ),
    ]
