# Generated by Django 2.1.2 on 2018-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='identifier',
            field=models.CharField(default=99999999, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(default=123456789, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
