# Generated by Django 2.1.2 on 2018-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181026_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
