# Generated by Django 2.1.2 on 2018-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181026_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
