# Generated by Django 2.1.2 on 2018-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181026_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='token',
            field=models.CharField(default='asdasdasdasd1212312312312', max_length=175),
            preserve_default=False,
        ),
    ]
