# Generated by Django 2.1.2 on 2018-10-27 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_request_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='asdasas', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo ya ha sido usado'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Este teléfono ya ha sido usado'}, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 2, 52, 1, 582566)),
        ),
    ]
