# Generated by Django 2.1.2 on 2018-10-27 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181027_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 2, 54, 42, 882237)),
        ),
    ]
