# Generated by Django 2.1.2 on 2018-10-27 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181027_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('emergency', models.CharField(choices=[('1', 'Emergencia 1'), ('2', 'Emergencia 2'), ('3', 'Emergencia 3'), ('4', 'Emergencia 4'), ('5', 'Emergencia 5')], max_length=1)),
                ('district', models.CharField(choices=[('1', 'Distrito 1'), ('2', 'Distrito 2'), ('3', 'Distrito 3'), ('4', 'Distrito 4'), ('5', 'Distrito 5')], max_length=1)),
                ('province', models.CharField(choices=[('1', 'Provincia 1'), ('2', 'Provincia 2'), ('3', 'Provincia 3'), ('4', 'Provincia 4'), ('5', 'Provincia 5')], max_length=1)),
                ('region', models.CharField(choices=[('1', 'Región 1'), ('2', 'Región 2'), ('3', 'Región 3'), ('4', 'Región 4'), ('5', 'Región 5')], max_length=1)),
                ('magnitude', models.CharField(choices=[('1', 'Magnitud 1'), ('2', 'Magnitud 2'), ('3', 'Magnitud 3'), ('4', 'Magnitud 4'), ('5', 'Magnitud 5')], max_length=1)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 10, 29, 3, 22, 36, 675164))),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('closed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Agent')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Authority')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='request',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='item',
            name='request',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='request',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='item',
            name='solicitude',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='solicitude',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
            preserve_default=False,
        ),
    ]
