# Generated by Django 2.1.2 on 2018-11-04 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181102_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitude',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 18, 31, 28, 631782)),
        ),
    ]
