# Generated by Django 2.1.2 on 2018-11-04 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181104_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 18, 32, 59, 584404)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
