# Generated by Django 2.1.2 on 2018-11-15 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181115_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitude',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='image_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 11, 10, 15, 777333)),
        ),
    ]
