# Generated by Django 2.1.2 on 2018-11-16 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20181115_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('RUC_or_DNI', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='help',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 2, 1, 27, 993007)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='magnitude',
            field=models.CharField(blank=True, choices=[('Magnitud 1', 'Magnitud 1'), ('Magnitud 2', 'Magnitud 2'), ('Magnitud 3', 'Magnitud 3'), ('Magnitud 4', 'Magnitud 4'), ('Magnitud 5', 'Magnitud 5')], max_length=20),
        ),
    ]
