# Generated by Django 2.1.2 on 2018-11-16 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20181116_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitude',
            name='focal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Focal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 9, 12, 41, 802495)),
        ),
    ]
