# Generated by Django 2.1.2 on 2018-11-16 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20181116_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 9, 33, 39, 403928)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='focal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Focal'),
        ),
    ]
