# Generated by Django 2.1.2 on 2018-11-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20181116_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaFocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('RUC_or_DNI', models.CharField(max_length=11)),
                ('identifier', models.CharField(max_length=11)),
                ('token', models.CharField(max_length=175)),
                ('photo_url', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya ha sido usado'}, max_length=40, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 9, 56, 42, 965420)),
        ),
    ]
