# Generated by Django 2.1.2 on 2018-11-19 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20181116_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 22, 22, 24, 742239)),
        ),
    ]
