# Generated by Django 2.1.2 on 2018-11-19 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20181118_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresafocal',
            name='phone',
            field=models.CharField(default=123456789, error_messages={'unique': 'Este teléfono ya ha sido usado'}, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 22, 25, 16, 978721)),
        ),
    ]
