# Generated by Django 2.1.2 on 2018-11-25 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20181120_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Help')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='remaining',
        ),
        migrations.RemoveField(
            model_name='item',
            name='help',
        ),
        migrations.RemoveField(
            model_name='solicitude',
            name='focal',
        ),
        migrations.AddField(
            model_name='focal',
            name='empresa_focal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.EmpresaFocal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 14, 21, 13, 237314)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='priority',
            field=models.CharField(blank=True, choices=[('Prioridad 1', 'Prioridad 1'), ('Prioridad 2', 'Prioridad 2'), ('Prioridad 3', 'Prioridad 3'), ('Prioridad 4', 'Prioridad 4'), ('Prioridad 5', 'Prioridad 5')], max_length=20),
        ),
        migrations.AddField(
            model_name='helpitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Item'),
        ),
        migrations.AddField(
            model_name='help',
            name='focal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Focal'),
        ),
        migrations.AddField(
            model_name='help',
            name='solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
    ]
