# Generated by Django 2.1.2 on 2018-11-30 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20181125_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresafocal',
            name='RUC_or_DNI',
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 10, 44, 46, 230321)),
        ),
    ]
