# Generated by Django 2.1.2 on 2018-12-03 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20181130_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default='Apellido', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 16, 9, 35, 952855)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='district',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='emergency',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='province',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='region',
            field=models.CharField(max_length=40),
        ),
    ]
