# Generated by Django 2.1.2 on 2018-12-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20181203_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitude',
            name='receiver_dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 10, 23, 55, 356286)),
        ),
    ]
