# Generated by Django 2.1.2 on 2018-12-04 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20181204_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='solicitude',
        ),
        migrations.AddField(
            model_name='help',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='help',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 14, 19, 19, 180724)),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='priority',
            field=models.CharField(blank=True, choices=[('Prioridad 1', 'Prioridad 1'), ('Prioridad 2', 'Prioridad 2'), ('Prioridad 3', 'Prioridad 3')], max_length=20),
        ),
    ]
