# Generated by Django 2.1.2 on 2018-12-05 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20181204_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='notification_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresafocal',
            name='notification_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 11, 14, 29, 516524)),
        ),
    ]
