# Generated by Django 2.1.2 on 2018-12-05 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20181205_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='notification_token',
            new_name='fcm_token',
        ),
        migrations.RenameField(
            model_name='empresafocal',
            old_name='notification_token',
            new_name='fcm_token',
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 11, 20, 50, 627734)),
        ),
    ]
