# Generated by Django 2.1.2 on 2018-12-07 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20181207_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='codeaccount',
            name='image',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 12, 24, 40, 9122)),
        ),
        migrations.AddField(
            model_name='notification',
            name='solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
    ]
