# Generated by Django 2.1.2 on 2018-12-07 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20181207_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeaccount',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 13, 36, 11, 964437)),
        ),
    ]
