# Generated by Django 2.1.2 on 2018-12-07 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20181207_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='solicitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 14, 24, 30, 206933)),
        ),
    ]
