# Generated by Django 2.1.2 on 2018-12-09 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20181207_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='solicitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Solicitude'),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 17, 5, 19, 625716)),
        ),
    ]
