# Generated by Django 2.1.2 on 2018-12-10 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20181209_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeaccount',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 21, 48, 17, 357016)),
        ),
    ]
